[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
]

dlc = []
optionals = []

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[Test]
extends = "default"
mission = "cba_settings_test.Stratis"
