name = "CVO CBA Settings Servermod"
prefix = "cvo_set"
mainprefix = "zrn"

[properties]
author = "CVO Team - Mr. Zorn"
url = "https://github.com/OverlordZorn/CVO-CBA-Settings"


[version]
# path = "addons/main/script_version.hpp" # Default
# major = 1 # Overrides path when set
# minor = 0
# PATCH = 1
git_hash = 2 # Default: 8